# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_lepiszcze.ipynb.

# %% auto 0
__all__ = ['LEPISZCZE_SUBMISSIONS', 'config', 'pipeline', 'results']

# %% ../nbs/00_lepiszcze.ipynb 4
from pathlib import Path

from .config.lightning_config import LightningBasicConfig, LightningAdvancedConfig
from .pipeline.lightning_classification import LightningClassificationPipeline

# %% ../nbs/00_lepiszcze.ipynb 7
LEPISZCZE_SUBMISSIONS = Path("../lepiszcze-submissions")
LEPISZCZE_SUBMISSIONS.mkdir(exist_ok=True, parents=True)

# %% ../nbs/00_lepiszcze.ipynb 8
config = LightningBasicConfig(
    learning_rate=0.01, max_epochs=1, max_seq_length=128, finetune_last_n_layers=0
)

# %% ../nbs/00_lepiszcze.ipynb 10
pipeline = LightningClassificationPipeline(
    dataset_name_or_path="clarin-pl/polemo2-official",
    embedding_name_or_path="allegro/herbert-base-cased",
    input_column_name="text",
    target_column_name="target",
    output_path=".",
    config=config
)

# %% ../nbs/00_lepiszcze.ipynb 13
results = pipeline.run()
print(results)
