LightingConfigSpace:
  embedding_name: allegro/herbert-base-cased
  devices:
    default: auto
  accelerator:
    default: auto
  max_epochs:
    name: max_epochs
    type: int_uniform
    low: 1
    high: 30
    step: 1
  mini_batch_size:
    name: batch_size
    type: log_int_uniform
    low: 8
    high: 64
    step: 1
  max_seq_length:
    name: max_seq_length
    value: None
  optimizer:
    name: optimizer
    type: categorical
    choices: ["Adam", "AdamW"]
  use_scheduler:
    name: use_scheduler
    type: categorical
    choices: [false, true]
  warmup_steps:
    name: warmup_steps
    type: int_uniform
    low: 0
    high: 200
    step: 10
  learning_rate:
    name: learning_rate
    type: log_uniform
    low: 1.0e-6
    high: 1.0e-1
  adam_epsilon:
    name: adam_epsilon
    type: uniform
    low: 0.0
    high: 1.0e-1
  weight_decay:
    name: weight_decay
    type: uniform
    low: 0.0
    high: 1.0e-1
  finetune_last_n_layers:
    name: finetune_last_n_layers
    type: categorical
    choices: [-1, 0, 1, 3, 5, 7, 9]
  classifier_dropout:
    name: classifier_dropout
    type: discrete_uniform
    low: 0.0
    high: 0.5
    q: 0.05