name: Deploy to GitHub Pages
on:
  push:
    branches: [271-create-documentation-and-library-presentation]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/quarto-ghp@master
        with: {pre: 1}