name: CI
on: pull_request

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.5]
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install deps
        run: poetry install -vv
      - name: Run tests
        run: poetry run pytest
  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.5]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install deps
        run: poetry install -vv
      - name: Check style
        run: poetry run black --check ./
      - name: Check types
        run: poetry run mypy --strict .
  publish:
#    needs:
#      - tests
#      - lint
    environment: Test deployment
    strategy:
      fail-fast: true
      matrix:
        python-version: [ 3.8 ]
        poetry-version: [ 1.1.5 ]
        os: [ ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install deps
        run: poetry install -vv
      - name: Build and publish
        run: |
          poetry version "$(git describe --tags)-SNAPSHOT"
          poetry build
          poetry config repositories.testpypi https://test.pypi.org/legacy
          poetry publish -r testpypi --username __token__ --password ${{ secrets.TEST_PYPI_API_TOKEN }}

