name: CI Docs
on: pull_request

jobs:
  test_doc_build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
        poetry-version: [ 1.3.2 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - uses: actions/cache@v3
        name: Load cached venv
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: main-venv-${{ runner.os }}-${{matrix.python-version}}-${{ hashFiles('**/poetry.lock') }}
      - name: Install deps
        run: poetry install -vv --no-interaction --no-root --extras "developer"
      - name: Make package editable
        run: poetry run pip install --editable ./
      - name: Build docs
        run: poetry run nbdev_docs
      - name: test docs build
        run: |
          poetry run nbdev_docs
          if [ -f "_docs/index.html" ]; then
            echo "docs built successfully."
          else
            echo "index page not found in rendered docs."
            ls -la
            ls -la _docs
            exit 1
          fi
